[pytest]
# -v 详细打印用例执行过程，显示每个用例名称与执行结果 -v越多越详细; -s 允许控制台输出print打印内容
# 把报告CSS、图片全部内嵌到html文件，单文件可直接打开分享; 每次生成前清空；把测试数据原始数据放进temps；指定默认浏览器
addopts = -v -v -s --self-contained-html  --clean-alluredir  --alluredir=.allure_results

# 指定用例路径
testpaths = ./testcase

# 自定义标记(指定某一个用例执行)
markers =
    api_login
    smoke



# 日志文件配置(需提前手动创建logs文件)
log_cli = 0
log_file = ./logs/pytest.log
log_file_level = info
log_cli_format = %(asctime)s | %(levelname)-8s | %(filename)s:%(lineno)-4d | %(message)s
log_file_date_format = %Y-%m-%d %H:%M:%S


[mysql]